### ISSUE TITLE
Yosemite supported?

### ISSUE THREAD

**Issue by hollodotme** [k3com/mac_dialer#2]
Hi,

I am on OS X Yosemite and have a SNOM 320.

In my `~/Library` folder is no such `/Scripts/Applications/Contacts` folder, but a 
`~/Library/Application Scripts/com.Apple.AddressBook` folder. 
Placing the plugin there has no effect at all.

Is there a solution for Yosemite or is it not supported at all?

Thank you,
Holger

**Comment by neffs** [comment]
The path was wrong, thanks for noticing.
~/Library/Application Scripts/com.Apple.AddressBook is the right path. It works for me on Yosemite.

You have to click on the label of the phone number, not the new call buttons.

**Comment by hollodotme** [comment]
Thank you for your fast reply, the info about the "click the label of the phone number" is missing in your README.md, too. :) I always tried the context menu of the number itself. :-/

**Comment by HansVanEijsden** [comment]
Oooohhh! Took me 7 hours to find out that I have to click on the label and not the context menu. Finally, it works after reading this issue here. THANKS!
