### ISSUE TITLE
Struggle on macOS Mojave

### ISSUE THREAD

**Issue by fepe89** [k3com/mac_dialer#3]
Hey, searched for this and was happy to find it. But looks like it`s not working on macOS Mojave (10.14.6) for snom. Is there any chance to check why? I will do research by my own and will contribute if i find any solution.

Great work and thanks in advance.

**Comment by neffs** [comment]
Unfortunately Apple removed support for these plugins in Mojave.

**Comment by HansVanEijsden** [comment]
I've solved it by creating this Automator Workflow script:


```
property callUrl : "http://user:password@10.0.1.10/command.htm?number="
on run {input, parameters}   

set theNumber to input
set theNumber to do shell script "echo \"" & theNumber & "\" |sed s/+49/0/ | sed s/[^0-9]//g"
  do shell script "curl " & callUrl & theNumber  
end run
```


Sorry about the Dutch language.
Automator:
![Schermafbeelding 2019-10-28 om 23 45 20](https://user-images.githubusercontent.com/11890145/67723736-2841cb80-f9dd-11e9-83f0-bb2c75f35446.png)
The context menu in the Contacts app (right click on the number, not the text in front of the number anymore):
![Schermafbeelding 2019-10-28 om 23 46 13](https://user-images.githubusercontent.com/11890145/67723770-44de0380-f9dd-11e9-9993-84f76cffd5ab.png)

Save the file as a workflow file and double click it to install. Activate it in System Preferences -> Keyboard Shortcuts -> Services.
More info: https://discussions.apple.com/thread/8552822
